on: [push]
jobs:
    pyinstaller-build:
        runs-on: windows-latest
        steps:
            - name: Create Executable
              uses: sayyid5416/pyinstaller@v1
              with:
                python_ver: '3.12'
                spec: 'main.spec'
                requirements: 'requirements.txt'
                upload_exe_with_name: 'netflix-surround-audio-trick.exe'
    release:
        needs: pyinstaller-build
        runs-on: ubuntu-latest
        steps:
            - name: Download Executable
              uses: actions/download-artifact@v4
              with:
                name: netflix-surround-audio-trick.exe
            - name: Upload to latest release
              uses: softprops/action-gh-release@v1
              with:
                files: netflix-surround-audio-trick.exe
                token: ${{ secrets.GITHUB_TOKEN }}
                append_body: true