on: [push]
jobs:
    pyinstaller-build:
        runs-on: windows-latest
        steps:
            - name: Create Executable
              uses: sayyid5416/pyinstaller@v1
              with:
                python_ver: '3.12'
                spec: 'main.spec'
                requirements: 'requirements.txt'
                upload_exe_with_name: 'netflix-surround-audio-trick.exe'
                options: --onefile, --name "Netflix Surround Audio Trick"
                